% yap script to print a cave generated by the cellular automaton (X is rock)
%
% usage:
% yap -L print_cave -- inputfile
%
% where inputfile contains rock/3 for one timepoint (or rock/2) and dimension 50x50
%


caveprint :-
	print_line(52),
	caveprint(1,51),  % print lines 1 to 50
	print_line(52).

% iterate over lines
caveprint(N,N).
caveprint(N,M) :-
	N < M,
	write('##'),
	caveprint_line(1,51,N),  % in line N, print cells 1 to 50
	NN is N+1,
	caveprint(NN,M).

% iterate over cells in line
caveprint_line(N,N,_) :- write('##'),nl.
caveprint_line(N,M,L) :-
	N < M,
	(
		rock(L,N) -> write('##'); write('  ')  % _ assumes a single time step in the input
	),
	NN is N+1,
	caveprint_line(NN,M,L).

print_line(0) :- nl.
print_line(N) :- N > 0, write('##'), NN is N-1, print_line(NN).

rock(A,B) :- rock(_,A,B).

:- unix(argv([File])),consult(File),caveprint.
